### ISSUE TITLE
TestSingleMessageWithReply: Intermittent failure "send on closed channel"

### ISSUE THREAD

**Issue by peterbroadhurst** [kaleido-io/ethconnect#66]
Intermittent build failure.
Occurred in Travis for #65 

```
time="2020-04-20T03:45:18Z" level=error msg="Unauthorized: badness - Message={Headers:{CommonHeaders:{ID: MsgType:TestSingleMessageWithReply Account:0xAA983AD2a0e0eD8ac639277F37be42F2A5d2618c Context:map[some:data]}}}"
time="2020-04-20T03:45:18Z" level=info msg="Sending reply: MsgContext[TestSingleMessageWithReply: reqOffset=in-topic:5:500 complete=false received=2020-04-20T03:45:18.473496879Z replied=2020-04-20T03:45:18.473552483Z replyType=Error]"
panic: send on closed channel
goroutine 38 [running]:
github.com/kaleido-io/ethconnect/internal/kldkafka.(*msgContext).Reply(0xc000108900, 0xcc39a0, 0xc0000d3cc0)
	/home/travis/gopath/src/github.com/kaleido-io/ethconnect/internal/kldkafka/kafkabridge.go:280 +0x52d
github.com/kaleido-io/ethconnect/internal/kldkafka.(*KafkaBridge).ConsumerMessagesLoop(0xc000182fc0, 0xccc020, 0xc0001d27c0, 0xccc060, 0xc0001d6930, 0xc000029950)
	/home/travis/gopath/src/github.com/kaleido-io/ethconnect/internal/kldkafka/kafkabridge.go:348 +0x435
created by github.com/kaleido-io/ethconnect/internal/kldkafka.setupMocks
	/home/travis/gopath/src/github.com/kaleido-io/ethconnect/internal/kldkafka/kafkabridge_test.go:205 +0x24a
```

**Comment by peterbroadhurst** [comment]
What's interesting here, is that it's apparently re-processing the first message from `TestSingleMessageWithReply`, but a second time after the `TestSecurityModule` has been registered inside of `TestSingleMessageWithNotAuthorizedReply` (when the `TestSingleMessageWithErrorReply` message should be sent).

**Comment by peterbroadhurst** [comment]
So there's a timing here when the `Message already in-flight` error message does not come out, and the duplicate actually gets processed - because the in-flight is flushed before the duplicate comes in.

**Comment by peterbroadhurst** [comment]
The problem was we were relying on async timing to validate duplicate detection.
So in https://github.com/kaleido-io/ethconnect/pull/65 I've added a separate synchronous test for duplicate detection in the Kafka bridge, and pulled it out of the original test that had a separate primary purpose.
